name: Javascriptmas CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
         echo "Installing dependencies"
         npm ci
         echo "Finished installing dependencies"

  lint:
    name: lint
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run lint
      run: |
         echo "Installing dependencies"
         npm ci
         echo "Finished installing dependencies"
         echo "Running lint"
         npm run lint
         echo "Finished running lint"

  
  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: ./coverage1.xml,./coverage2.xml 
        flags: unittests
        name: codecov-umbrella 
        fail_ci_if_error: true 
        verbose: true 
    - name: Run tests
      run: |
         echo "Installing dependencies"
         npm ci
         echo "Finished installing dependencies"
         echo "Running tests"
         npm run test
         echo "Finished running tests"

  